blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth.views import LoginView,PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView



app_name='blog'
urlpatterns = [
	
	path('',views.home,name='home'),
	path('post_new/',views.post_new,name='post_new'),
	path('post_list/',views.post_list,name='post_list'),
    path('login/',LoginView.as_view(),name='login'),
    path('signup/',views.signup, name='signup'),
    path('logout/',views.log_out,name='logout'),
    #path('myblogs/',views.myblogs,name='myblogs'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/detail/', views.post_detail, name='post_detail'),
    path('password_reset/',PasswordResetView.as_view(template_name="blog/password_reset_form.html",subject_template_name='blog/password-reset/password_reset_subject.txt',email_template_name='blog/password-reset/password_reset_done.html'),name='password_reset'),
    path('blog/password_reset/done/',PasswordResetDoneView.as_view(template_name="blog/password_reset_done.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name="blog/password-reset/password_reset_confirm.html"),name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(template_name="blog/password-reset/password_reset_complete.html"), name='password_reset_complete'),
    path('subscribe/',views.subscriber,name='subscribe'),
]

country/urls.py
from django.urls import include,path

from . import views


app_name='country'
urlpatterns = [
    path('', views.PersonListView.as_view(), name='person_changelist'),
    path('add/', views.PersonCreateView.as_view(), name='person_add'),
    path('<int:pk>/', views.PersonUpdateView.as_view(), name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('uploads/simple', views.simple_upload, name='simple_upload'),
    path('uploads/form/', views.model_form_upload, name='model_form_upload'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name='blog/home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('django.contrib.auth.urls')),
    path('country/',include('country.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

country/models.py
from django.db import models

# Create your models here.


class Country(models.Model):
	name = models.CharField(max_length=200)


	def __str__(self):
		return self.name




class State(models.Model):
	country = models.ForeignKey(Country,on_delete=models.CASCADE)
	name = models.CharField(max_length=200)


	def __str__(self):
		return self.name



class Person(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

country/forms.py
from django import forms
from .models import Country,State,Person,Document



class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'birthdate', 'country', 'state')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['state'].queryset = State.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['state'].queryset = State.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['state'].queryset = self.instance.country.state_set.order_by('name')



class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document', )

country/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,CreateView, UpdateView
from django.urls import reverse_lazy
from .models import Country,State,Person,Document

from .forms import PersonForm,DocumentForm
from django.core.files.storage import FileSystemStorage

# Create your views here.



class PersonListView(ListView):
    model = Person

    context_object_name = 'people'

class PersonCreateView(CreateView):
    model = Person

    form_class = PersonForm
    success_url = reverse_lazy('person_changelist')

class PersonUpdateView(UpdateView):
	model = Person

	form_class = PersonForm
	success_url = reverse_lazy('person_changelist')


def load_cities(request):
    country_id = request.GET.get('country')
    cities = State.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'country/city_dropdown_list_options.html', {'cities': cities})



def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'country/simple_upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'country/simple_upload.html')





def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = DocumentForm()
    return render(request, 'country/model_form_upload.html', {
        'form': form
    })

country/templates/country/city_dropdown_list_options.html
<option value="">---------</option>
{% for state in cities %}
<option value="{{ state.pk }}">{{ state.name }}</option>
{% endfor %}

country/templates/country/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <h2>Person Form</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'country:person_changelist' %}">Nevermind</a>
  </form>
{% endblock %}

country/templates/country/model_form_upload.html
{% extends 'blog/base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

country/templates/country/person_form.html
{% extends 'blog/base.html' %}

{% block content %}

  <h2>Person Form</h2>

  <form method="post" id="personForm" data-cities-url="{% url 'country:ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'country:person_changelist' %}">Nevermind</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_country").change(function () {
      var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var countryId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'country': countryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_state").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

country/templates/country/person_list.html
{% extends 'blog/base.html' %}

{% block title %}Jakhar Infotech Module{% endblock %}

{% block content %}
  <h2>Jakhar infotech » Clients Report</h2>

  <p>
    <a href="{% url 'country:person_add' %}">Add person</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>Country</th>
        <th>State</th>
      </tr>
    </thead>
    <tbody>
      {% for person in people %}
        <tr>
          <td><a href="{% url 'country:person_change' person.pk %}">{{ person.name }}</a></td>
          <td>{{ person.birthdate }}</td>
          <td>{{ person.country.name }}</td>
          <td>{{ person.state.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'country:person_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

country/templates/country/simple_upload.html
{% extends "blog/base.html" %}


{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}