blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth.views import LoginView,PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView



app_name='blog'
urlpatterns = [
	
	path('',views.home,name='home'),
	path('post_new/',views.post_new,name='post_new'),
	path('post_list/',views.post_list,name='post_list'),
    path('login/',LoginView.as_view(),name='login'),
    path('signup/',views.signup, name='signup'),
    path('logout/',views.log_out,name='logout'),
    #path('myblogs/',views.myblogs,name='myblogs'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/detail/', views.post_detail, name='post_detail'),
    path('password_reset/',PasswordResetView.as_view(template_name="blog/password_reset_form.html",subject_template_name='blog/password-reset/password_reset_subject.txt',email_template_name='blog/password-reset/password_reset_done.html'),name='password_reset'),
    path('blog/password_reset/done/',PasswordResetDoneView.as_view(template_name="blog/password_reset_done.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name="blog/password-reset/password_reset_confirm.html"),name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(template_name="blog/password-reset/password_reset_complete.html"), name='password_reset_complete'),
    path('subscribe/',views.subscriber,name='subscribe'),
]

country/urls.py
from django.urls import include,path

from . import views


app_name='country'
urlpatterns = [
    path('', views.PersonListView.as_view(), name='person_changelist'),
    path('add/', views.PersonCreateView.as_view(), name='person_add'),
    path('<int:pk>/', views.PersonUpdateView.as_view(), name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('uploads/simple', views.simple_upload, name='simple_upload'),
    path('uploads/form/', views.model_form_upload, name='model_form_upload'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name='blog/home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('django.contrib.auth.urls')),
    path('country/',include('country.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class CustomUser(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    dob = models.DateField(null=True, blank=True)
    

    def __str__(self):
        return self.username

class Post(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to ='blog/img',null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments',null=True)
    author = models.CharField(max_length=200)
    reply = models.ForeignKey('Comment',on_delete=models.CASCADE,null=True,related_name='replies')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)
    active = models.BooleanField(default=True)


    def approved(self):
        self.approved_comments = True
        self.save()

    def __str__(self):
        return self.text

        



		




















"""class Profile(models.Model):
    username = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to ='myblog/img',null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title"""
		

	

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser,Post,Comment
from django.utils import timezone



class UserLoginForm(UserCreationForm):
	class Meta:
		model = CustomUser
		fields = ('username','email','bio','dob')


class PostForm(forms.ModelForm):
	#author = CustomUser.username

	class Meta:
		model = Post
		fields = ('title', 'text','image')
	


class SubscriberForm(forms.Form):
	email = forms.EmailField(required=True)
	subject = forms.CharField(required=True)


class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('author','text',)

	
		

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from .forms import UserLoginForm,PostForm,SubscriberForm,CommentForm
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth import login, authenticate,logout
from .models import CustomUser,Post,Comment
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.mail import send_mail,EmailMessage
from django.template.loader import render_to_string
from myproject.settings import EMAIL_HOST_USER
from django.db.models import Count

# Create your views here.


def home(request):
    return render(request,'blog/home.html')

def log_out(request):
    logout(request)
    return redirect('blog:home')

def signup(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:login')
    else:
        form = UserLoginForm()
        return render(request, 'blog/signup.html', {'form': form})

def post_list(request):
    posts = Post.objects.all()
    print(posts)
    return render(request, 'blog/post_list.html', {"posts" : posts })

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            #print(post.author)
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_list')
    
    else:

        form = PostForm()
    return render(request, 'blog/post_new.html', {'form': form})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
     # list of active parent comments
    comments = post.comments.filter(active=True, reply__isnull=True)
    if request.method == 'POST':
        # comment has been added
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            reply_obj = None
            # get parent comment id from hidden input
            try:
                # id integer e.g. 15
                reply_id = int(request.POST.get('reply_id'))
            except:
                reply_id = None
            # if parent_id has been submitted get parent_obj id
            if reply_id:
                reply_obj = Comment.objects.get(id=reply_id)
                # if parent object exist
                if reply_obj:
                    # create replay comment object
                    replay_comment = comment_form.save(commit=False)
                    # assign parent_obj to replay comment
                    replay_comment.reply = reply_obj
            # normal comment
            # create comment object but do not save to database
            new_comment = comment_form.save(commit=False)
            # assign ship to the comment
            new_comment.post = post
            # save
            new_comment.save()
            return redirect('blog/post_detail',pk)
    else:
        comment_form = CommentForm()
    
    return render(request,'blog/post_detail.html',{'post':post,'comments': comments,
                   'comment_form': comment_form})



    """print(post.author)
    user = request.user
    print(user)
    return render(request, 'blog/post_detail.html', {'post': post,"user":user})"""



@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_list')
            
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_new.html', {'form': form})


#how to send html template through email
def subscriber(request):
    form = SubscriberForm(request.POST)
    if request.method == "POST":
       
        if form.is_valid():
            email = form.cleaned_data['email']
            message_html = render_to_string('blog/email_sent.html')
            #plain_message = strip_tags(html_message)
            subject = form.cleaned_data['subject']
            #try:
            #in this way email format send in template
            send_mail(subject,recipient_list=[email],from_email=EMAIL_HOST_USER,message=subject,html_message=message_html)
            #except BadHeaderError:
                #return HttpResponse('Invalid header found.')
            return HttpResponse("Sucess!Thank you for subscribe")
    return render(request, "blog/subscribe.html", {'form': form})

"""def sucess(request):
    return HttpResponse("Sucess!Thank you for subscribe")"""

"""def add_comment_to_post(request,pk):

    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)

        if form.is_valid():

            Comment = form.save(commit=False)
            Comment.post = post
            Comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
        return render(request, 'blog/add_comment_to_post.html', {'form': form}) 


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=Comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=Comment.post.pk)"""



    
            

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
       <title>blog world</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script>
            $(document).ready(function(){
                $('button').click(function(){
                    alert("Save")
                });
            });

        </script>
    </head>
    </head>
    <body>
        
        <div class="page-header">
           
            <a href="{% url 'blog:post_new'  %}" class="top-menu" ><span class="glyphicon glyphicon-plus"></span></a>
            <a href="{% url 'blog:login'%}" class="top-menu " >Login</a>
            <h1><a href="{% url 'blog:post_list' %}">Blog </a>
                <a href="{% url 'country:person_changelist' %}">Country</a>
                {% if user.is_authenticated %}
                	
                	<a href="{% url 'blog:logout'%}">logout</a>
                {% else %}
                	<a href="{% url 'blog:signup'%}">	signup</a>

                {% endif %}
            </h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">


                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>

<footer>
    <div class= "navbar navbar-inverse navbar-static-bottom" role="navigation">
    <div class="navbar-text pull-left">
    </div>
    <div class= "navbar-text pull-right">
<!-- Add in your social media / github links here -->
        <a href="https://github.com/clarkdatalabs">
            <i class="fa fa-github-square fa-2x"></i></a>
    </div>
    <!--Below is the copyright information for the site. You can fill in your own here.-->
    <div class="page-header">
    &copy; Jakhar infotech, 2020
    </div>
     <div class="page-header">
        <a href="{% url 'blog:subscribe' %}">Subscribe</a>
        
    </div>
    </div>  
</footer>
</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'blog:signup' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'blog:login' %}">login</a> |
  <a href="{% url 'blog:signup' %}">signup</a>
{% endif %}
{% endblock %}

blog/templates/blog/email_sent.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Emal-Confirmation</title>

    <link href="{{base_url}}static/assets/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="{{base_url}}static/assets/js/bootstrap.min.js"></script>
    <script src="{{base_url}}static/assets/js/jquery-1.11.1.min.js"></script>
</head>

<body> 

    <section id="email_confirmation">
        <div id="mailsub" class="notification" align="center">

            <table width="100%" border="0" cellspacing="0" cellpadding="0" style="min-width: 320px;"><tr><td align="center" bgcolor="#eff3f8">

            <table border="0" cellspacing="0" cellpadding="0" class="table_width_100" width="100%" style="max-width: 680px; min-width: 300px;">
                <tr>
                    <td>
                        <!-- padding -->
                        <div style="height: 80px; line-height: 80px; font-size: 10px;"> </div>
                    </td>
                </tr>
                <!--header -->
                <tr>
                    <td align="center" bgcolor="#0d469f">
                        <!-- padding -->
                        <div style="height: 15px; line-height: 15px; font-size: 10px;"> </div>

                        <table width="90%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td align="center">
                                    <!-- Item -->
                                    <div class="mob_center_bl" style="display: inline-block; width: 115px;">
                                        <table style="text-align: center;" class="mob_center" width="115" border="0" cellspacing="0" cellpadding="0" align="center" style="border-collapse: collapse;">
                                            <tr><td align="center" valign="middle">
                                                <!-- padding -->
                                                <div style="height: 20px; line-height: 20px; font-size: 10px;"> </div>
                                                <table width="115" border="0" cellspacing="0" cellpadding="0" >
                                                    <tr><td align="center" valign="top" class="mob_center">
                                                        <a href="#" target="_blank" style="color: #ffff;
                                                        font-family: Arial, Helvetica, sans-serif;
                                                        font-size: 31px;">
                                                        Jakhar infotech</a>
                                                    </td></tr>
                                                </table>                        
                                            </td></tr>
                                        </table>
                                    </div>
                                    <!-- Item END-->
                                </td>
                            </tr>
                        </table>
                        <!-- padding -->
                        <div style="height: 30px; line-height: 30px; font-size: 10px;"> </div>
                    </td>
                </tr>
                <!--header END-->

                <!--content 1 -->
                <tr>
                    <td align="center" bgcolor="#fbfcfd">
                        <table width="90%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td align="center">
                                    <!-- padding -->
                                    <div style="height: 30px; line-height: 30px; font-size: 10px;"> </div>
                                    <div style="line-height: 44px;">
                                        <font face="Arial, Helvetica, sans-serif" size="5" color="#57697e" style="font-size: 34px;">
                                            <span style="font-family: Arial, Helvetica, sans-serif;font-size: 15px;color: #131414;display: block;margin-block-start: 1.33em;margin-inline-start: 0px;margin-inline-end: 0px;font-weight: bold;text-align: center;">
                                            
                                            </span>
                                        </font>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <div style="line-height: 24px;">
                                        <font face="Arial, Helvetica, sans-serif" size="4" color="#57697e" style="font-size: 15px;">
                                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 15px; color: #000;">
                                            You Have Succesfully Subscribe 
                                            <br><br>
                                            <!--<strong>OTP {{otp}}</strong> expires at <strong>{{time}}</strong>-->
                                            
                                        </span></font>
                                    </div>
                                    <!-- padding -->
                                    <div style="height: 15px; line-height: 15px; font-size: 10px;"> </div>
                                </td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <div style="line-height: 24px;">
                                        <font face="Arial, Helvetica, sans-serif" size="4" color="#57697e" style="font-size: 15px;">
                                        <span style="font-family: Arial, Helvetica, sans-serif; font-size: 15px; color: #000;">
                                            If you did not perform this action, please contact us immediately at <a href="mailto:support@jakharinfotech.com" target="_blank" data-saferedirecturl="">support@jakharinfotech.com</a> to freeze your account and prevent any misuse or damages.
                                        </span></font>
                                    </div>
                                </td>
                            </tr>
                        </table>        
                    </td>
                </tr>
                <!--content 1 END-->
                <!--footer -->
                <tr>
                    <td class="iage_footer" align="center" bgcolor="#ffffff">
                        
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr><td align="center">
                                <!-- padding -->
                                    <div style="height: 15px; line-height: 15px; font-size: 10px;"> </div>
                                <font face="Arial, Helvetica, sans-serif" size="3" color="#96a5b5" style="font-size: 13px;">
                                <span style="font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: #96a5b5;">
                                    2018 © Jakhar Infotech. ALL Rights Reserved.
                                </span></font>              
                            </td></tr>          
                        </table>
                        
                        <!-- padding -->
                        <div style="height: 30px; line-height: 30px; font-size: 10px;"> </div>  
                    </td>
                </tr>
                <!--footer END-->

                <tr>
                    <td>
                        <!-- padding -->
                        <div style="height: 80px; line-height: 80px; font-size: 10px;"> </div>
                    </td>
                </tr>
            </table>
             
            </td></tr>

            </table>
                        
            </div> 
    </section>

    <script src="{{base_url}}static/assets/js/jquery.bootstrap.wizard.js"></script>
       
    </script>
</body>

</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'blog:logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'blog:login' %}">login</a> |
  <a href="{% url 'blog:signup' %}">signup</a>
{% endif %}


{% endblock %}

blog/templates/blog/password_reset_done.html
{% extends 'blog/base.html' %}

{% block title %}Email Sent{% endblock %}

{% block content %}
  <h1>Check your inbox.</h1>
  <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
  <p> if you don't recieve an email,please make sure that you have entered ,otherwise check spam folder </p>

{% endblock %}

blog/templates/blog/password_reset_form.html
{% extends 'blog/base.html' %}

{% block title %}Forgot Your Password?{% endblock %}

{% block content %}
  <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">

    <a href="{% url 'blog:post_list' %}">Back</a>
  </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
        {% if error_message %}
        <p> {{ error_message }}</p>
        {% endif %}
        {% if post.image %}
            <img src="{{ post.image.url}}" height="250" width="400">
        {% endif %}
        
    </div>

   <!-- Comments Form --> 
<h2>Add a new comment</h2>
<form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <button type="submit">Add comment</button>
</form>

<!-- Comment with nested comments -->
{% for comment in comments %}
    <div class="comment" style="background-color: white">
        <p class="info">{{ comment.author}} | {{ comment.created_date }}</p>
            {{ comment.text|linebreaks }}

        {% for replay in comment.replies.all %}
            <p class="info">{{ replay.author }} | {{ replay.created_date }}</p>
            <li>{{ replay.text }}</li>
        {% endfor %}

        <h5>Replay</h5>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <!-- Hidden input for parent comment.id -->
            <input type="hidden" name="parent_id" value="{{ comment.id }}">
            <input class="btn btn-primary" type="submit" value="Replay">
        </form>
    </div>
{% empty %}
<h4>There are no comments yet.</h4>
{% endfor %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in posts %}
    	
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
            <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
            {% if post.image %}
            <p><img src="{{ post.image.url}}" height="250" width="400"></p>
            {% endif %}
            
            
        </div>
        
    {% endfor %}
{% endblock %}

blog/templates/blog/post_new.html
{% extends 'blog/base.html' %}

{% block content %}
	<h2>New post</h2>
	<form method="POST" class="post-form" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Save</button>
	</form>
{% endblock %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="post-form">
	<h2>sign up</h2>

	<form method="post">
  		{% csrf_token %}
  		{{ form.as_p }}
  		<button type="submit">sign up</button><a href="{% url 'blog:login' %}">login</a>
	</form>
</div>
{% endblock %}

blog/templates/blog/subscribe.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>Subscribe</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
</form>

{% endblock %}